// <auto-generated />
namespace VidlyMovies.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Required));
        
        string IMigrationMetadata.Id
        {
            get { return "202002091151166_[Required]"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
